# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: keepalived_exporter

builds:
  - binary: "{{ .ProjectName }}"
    id: "amd64"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

upx:
  - enabled: true

archives:
  - id: archive
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
    files:
      - README.md

snapshot:
  name_template: "{{ .Tag }}-snapshot"

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum
    output: true
